-- 创建 memo 表
create table public.memo (
  id bigint generated by default as identity primary key,
  uid uuid default gen_random_uuid(),
  created_ts bigint not null,
  updated_ts bigint not null,
  category text default 'daily'::text,
  target_date text,
  completion_status text default 'pending'::text,
  content text default ''::text,
  pinned boolean default false,
  archived boolean default false
);

-- 创建 daily_plan 表
create table public.daily_plan (
  id bigint generated by default as identity primary key,
  plan_date text not null,
  title text not null,
  description text default ''::text,
  category text default 'daily'::text,
  completed boolean default false,
  priority integer default 0,
  created_ts bigint not null,
  updated_ts bigint not null,
  completed_ts bigint
);

-- 开启 Row Level Security (RLS) - 暂时允许所有读写方便开发
-- 注意: 生产环境建议配置详细策略
alter table public.memo enable row level security;
alter table public.daily_plan enable row level security;

create policy "允许匿名所有操作 memo"
on public.memo
for all
to anon
using (true)
with check (true);

create policy "允许匿名所有操作 daily_plan"
on public.daily_plan
for all
to anon
using (true)
with check (true);

-- 索引: 加速 getMemos 查询 (WHERE archived=false ORDER BY pinned DESC, created_ts DESC)
create index if not exists idx_memo_list
  on public.memo (archived, pinned desc, created_ts desc);
